### ISSUE TITLE
Which licence?

### ISSUE THREAD

**Issue by svenvdvoort** [Voronenko/PHPOTP#10]
Hello,
I was wondering what licence your code is published under, because I would like to use it in a commercial product. And how about the base32 code, is it under a particular licence?
Thanks for the time and effort you put into this easy-to-use library!

**Comment by Voronenko** [comment]
MIT, you are free to adapt , but make sure you checked this thread on similar topic https://github.com/Voronenko/PHPOTP/issues/9

Re: base32static, again in that's form it was included for demonstration purposes, so you can use debugger inside all the steps.

In production, you might consider using native PHP function:  http://php.net/manual/en/function.base-convert.php

**Comment by Voronenko** [comment]
For function used in scope of demo, you might contact author at bryan at bryanruiz dot com  && check with him.

**Comment by svenvdvoort** [comment]
Okey, thanks for the quick reply! I will be using the PHP native function for production then. Shall I close the issue or will you add the licence to the code?

**Comment by Voronenko** [comment]
added.
