### ISSUE TITLE
Authentication failed.

### ISSUE THREAD

**Issue by harishincipio** [Voronenko/PHPOTP#14]
Hey Guys,

I have integrated the code with my application and it has been working perfectly for the past 2 years, but all of a sudden the integration stopped working. When a user enters the authentication code it's returning an 'Authentication Failed' error. Can someone please help me on how to get this working again.

Thanks,

Harish

**Comment by Voronenko** [comment]
I would switch to some fully tested library, as this one was for illustration purposes only.

Nevertheless, I would check with some other OTP application, and check if time is right on the server part.
