### ISSUE TITLE
URL in getBarCodeUrl is out of date.

### ISSUE THREAD

**Issue by rdewalt** [Voronenko/PHPOTP#2]
http://www.google.com/chart no longer works.  I've found that http://chart.apis.google.com/chart does the same thing.  

https://github.com/rdewalt/PHPOTP/commit/bb24d402fa0ae9ebf4355515889d410d0cc39c39

**Comment by Voronenko** [comment]
Thanks!

The best way would be for you to open pull request with changes - so I can incorporate it.

See

https://help.github.com/articles/fork-a-repo/
